### ISSUE TITLE
Where for config global?

### ISSUE THREAD

**Issue by thearabbit** [zimme/meteor-collection-timestampable#11]
Where I should config global at `common` or `server`?

**Comment by thearabbit** [comment]
Ok now I understand about this.

**Comment by zimme** [comment]
For this package the global configuration should go in `common` because the behaviour is stubbed in `client` but actually set on `server`.

Would it have helped if I mentioned where the global configuration should be set?

**Comment by zimme** [comment]
I've documented the global configuration some more now, hopefully no one else will be confused.
