### ISSUE TITLE
Values of createdBy and updatedBy

### ISSUE THREAD

**Issue by 57even** [zimme/meteor-collection-timestampable#12]
Nice package but why are createdBy and updatedBy populated with 0? Should these be populated manually? I guess I can change it with `systemId: '0'` but shouldn't a default 'invalid' ID be -1 or null to indicate that no ID actual was found?

**Comment by zimme** [comment]
When there isn't a user id i.e. no user is logged in and performed the action. I assume it's the system which performed the action which I default to `0` but you can as you said change it to whatever you'd like.

So you can say create a "System" user and use that users' id as the `systemId` and print out a nice message about that it was the system which last changed the document.

If there's a need for it maybe I should see if I can't add support for differentiating between when it's an anonymous client action and a server initiated action and have the two things use different ids.

**Comment by zimme** [comment]
I'm closing this as it's answered and isn't really a feature request.

Just @mention me if you want me to re-open.
