### ISSUE TITLE
Override or circumvent?

### ISSUE THREAD

**Issue by roelvan** [zimme/meteor-collection-timestampable#17]
I need to run a migration (production db) that splits documents. The new inserted document should get the same createdAt field as the original one.

I tried these collection2 settings, but it still uses the current date instead of the old one:

```
Collection.insert newDoc,
  validate: false
  filter: false
  getAutoValues: false
```

I'd rather not switch off the timestampable behaviour in my production codebase.
Any other way to switch the behaviour off for a certain query? Thanks!

**Comment by roelvan** [comment]
Sorry there is already a similar issue. Can be closed I guess. Sorry!

**Comment by zimme** [comment]
I'll close this and give you both a temp solution in the other thread.
