### ISSUE TITLE
what `systemId ` mean?

### ISSUE THREAD

**Issue by thearabbit** [zimme/meteor-collection-timestampable#21]
what `systemId ` mean?

**Comment by zimme** [comment]
systemId: Optional. Set to 'string' to change the id representing the system.

It's the userId to use when an update/insert/remove action is run by server code that was not requested by a logged in user. e.g. If you do an insert in server code when meteor starts

**Comment by thearabbit** [comment]
Oh, thanks for your reply.
Before my startup fixture alway don't have `createdBy `
