### ISSUE TITLE
Conflict with last version of aldeed:autoform

### ISSUE THREAD

**Issue by appshore** [zimme/meteor-collection-timestampable#3]
$ meteor add zimme:collection-timestampable
 => Errors while adding packages:             
                                              
While selecting package versions:
error: conflict: constraint aldeed:autoform@4.0.0 is not satisfied by 5.0.2.
Constraints on aldeed:autoform come from:
<top level>
zimme:collection-timestampable@1.0.0

**Comment by zimme** [comment]
My bad. I've added support for it but I didn't publish a new version...

I'll fix it today.

**Comment by appshore** [comment]
Works fine. Thank you!
