### ISSUE TITLE
updatedBy doesn't change when updating documents

### ISSUE THREAD

**Issue by dominikzborowski** [zimme/meteor-collection-timestampable#9]
@zimme I've noticed that when I update documents `updatedBy` doesn't change. As I've noticed it's because of this condition in before update hook:

```
if (updatedBy && (doc[updatedBy] == null)) {
  return $set[updatedBy] = userId;
}
```
So seems that `updatedBy` is only set when it's `null`. Is that on purpose?

**Comment by zimme** [comment]
This might be an oversight on my part, I'll have a look this weekend unless I can carve out some time earlier.

**Comment by zimme** [comment]
Ok, had a quick look just now. It's expected behaviour, I made it this way so that you could specify which user it's updated by.

So if your modifier contains `updatedBy` then it uses that value, if it's not set then use the automatic value.

I'll have to think on this a while to see if it's necessary to have it this way, maybe an option to disable this behaviour is needed.

Do you know if the modifier you're using is containing the old value of `updatedBy`?

**Comment by dominikzborowski** [comment]
I'm using default setup `Posts.attachBehaviour('timestampable')`. 

Maybe I will describe the flow. When I do insert on collection it adds document with `createdBy` and `createdAt` fields as expected. Next I do update on this doc and it adds `updatedBy` and `updatedAt` fields. Till now is fine. But once I log in into another user account and try to update same document only `updatedAt` chenges, the `updatedBy` field keep old user id. I've expected that `updatedBy` will change to new user.

Can you check if you can replicate that?

**Comment by zimme** [comment]
I will still need the update modifier you're using to change the document.
```js
Meteor.users.update(Meteor.userId(), {....});
```
`{...}`, I need this part.

**Comment by dominikzborowski** [comment]
My update code looks like this:

```
Posts.update id,
      $set:
        status: status
```

**Comment by dominikzborowski** [comment]
Btw, I use now extra hook to get things working like this:
```
Posts.before.update (userId = 0, doc, fieldNames, modifier, options) ->
  $set = modifier.$set ?= {}
  $set['updatedBy'] = userId
```

so it always change `updatedBy` to current user on doc update

**Comment by zimme** [comment]
I've verified this, it's not working as expected. I'll try and fix this as soon as possible.

**Comment by dominikzborowski** [comment]
Reconsider this change:

```
if updatedby and not modifier.$set[updatedby]?
    $set[updatedby] = userid
```

**Comment by zimme** [comment]
Yes, I realized I check the current doc and not the intended changes

`$set[updatedBy]` should be checked

**Comment by zimme** [comment]
`meteor add zimme:collection-timestampable@1.0.7-rc.1`

**Comment by dominikzborowski** [comment]
Awesome, thanks!
